### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "kotlinx.datetime.Instant" on path: DexPathList

### ISSUE THREAD

**Issue by Stxtics** [tuyen-vuduc/dotnet-binding-utils#83]
I'm sorry if this is an issue on my end but if anyone can help that would be greatly appreciated.

I'm working with .NET Maui to add an Android module that I have made into a .NET Maui app.

The .NET Maui binding library was building but I recently changed the module where I added the "org.jetbrains.kotlinx:kotlinx-serialization-json" and "org.jetbrains.kotlinx:kotlinx-datetime" libraries. 

To resolve a ClassNotFoundException I experienced I added the "Org.Jetbrains.Kotlinx.KotlinxSerializationJson" package from this repo. 

However, after that I have been experiencing the error "java.lang.ClassNotFoundException: Didn't find class "kotlinx.datetime.Instant" on path: DexPathList".
To try to resolve that I have added the "Org.Jetbrains.Kotlinx.KotlinxDatetime" package but I am still experiencing the issue. 

Here is some of the stack trace if that helps.

[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/datetime/Instant;
[MonoDroid]  ---> Java.Lang.ClassNotFoundException: Didn't find class "kotlinx.datetime.Instant" on path: DexPathList[[zip file "/data/app/~~PSuy2uBQfzuCQKD6Hq1bwQ==/com.*.*mauiwrapper-qP0pRP6fSMex7UgRVkqW4A==/base.apk"],nativeLibraryDirectories=[/data/app/~~PSuy2uBQfzuCQKD6Hq1bwQ==/com.*.*mauiwrapper-qP0pRP6fSMex7UgRVkqW4A==/lib/arm64, /data/app/~~PSuy2uBQfzuCQKD6Hq1bwQ==/com.*.*mauiwrapper-qP0pRP6fSMex7UgRVkqW4A==/base.apk!/lib/arm64-v8a, /system/lib64]]
[MonoDroid] 
[MonoDroid]   --- End of managed Java.Lang.ClassNotFoundException stack trace ---
[MonoDroid] java.lang.ClassNotFoundException: Didn't find class "kotlinx.datetime.Instant" on path: DexPathList[[zip file "/data/app/~~PSuy2uBQfzuCQKD6Hq1bwQ==/com.*.*mauiwrapper-qP0pRP6fSMex7UgRVkqW4A==/base.apk"],nativeLibraryDirectories=[/data/app/~~PSuy2uBQfzuCQKD6Hq1bwQ==/com.*.*mauiwrapper-qP0pRP6fSMex7UgRVkqW4A==/lib/arm64, /data/app/~~PSuy2uBQfzuCQKD6Hq1bwQ==/com.*.*mauiwrapper-qP0pRP6fSMex7UgRVkqW4A==/base.apk!/lib/arm64-v8a, /system/lib64]]
[MonoDroid] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
[MonoDroid] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[MonoDroid] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[MonoDroid] 	at com.*.*androidmodule.models.Scenario.<clinit>(ScenarioModels.kt:70)
[MonoDroid] 	at com.*.*.services.ScenarioWebService$getScenario$2.invokeSuspend(ScenarioWebService.kt:105)
[MonoDroid] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[MonoDroid] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
[MonoDroid] 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
[MonoDroid] 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
[MonoDroid] 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
[MonoDroid] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
[MonoDroid] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
[MonoDroid] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
[MonoDroid] 
[MonoDroid]   --- End of managed Java.Lang.ClassNotFoundException stack trace ---

**Comment by tuyen-vuduc** [comment]
@Stxtics There is a bug. I will check.

**Comment by tuyen-vuduc** [comment]
https://github.com/tuyen-vuduc/dotnet-binding-utils/pull/84

Plz check out latest build v0.6.1 for the nuget package then.

**Comment by Stxtics** [comment]
Thank you! That has fixed the issue I was getting.
