### ISSUE TITLE
Need more info!

### ISSUE THREAD

**Issue by adarshchiniwar-smartq** [tuyen-vuduc/dotnet-binding-utils#86]
Hi,

I am trying to integrate the maven repository in our project. I have followed the steps and I have added Xamarin.AndroidBinderators since I couldn't find the exact specified library, Once I build the app it builds successfully but I am not getting where all the dependencies will be downloaded and how can I use them in .net maui project.

Can you please help me with the sample maui application?

Thanks,
Adarsh

**Comment by tuyen-vuduc** [comment]
This project doesn't use `Xamarin.AndroidBinderators`.

**Comment by adarshchiniwar-smartq** [comment]
Hi

I am not able to find dotnet add package Binderators.Gradle Can you please help me with this?

Thanks,
Adarsh

**Comment by tuyen-vuduc** [comment]
Hi @adarshchiniwar-smartq ,

Can you describe what you want to achieve?

**Comment by adarshchiniwar-smartq** [comment]
Hi @tuyen-vuduc ,

We have got a requirement to integrate the payment terminal in .net maui app. the vendor has provided us with the maven repository which is secured by credentials. I have downloaded like 50 to 60 .aar and .jar files using android studio. How can I create a binding library using such large number of .aar and .jar files?

Thanks,
Adarsh

**Comment by tuyen-vuduc** [comment]
Hi @adarshchiniwar-smartq .

Have you managed it to get it work?

What is that payment terminal? Are those mentioned AAR/JAR files hosted using Maven?

**Comment by tuyen-vuduc** [comment]
Hi @adarshchiniwar-smartq ,

How is it going?
